### ISSUE TITLE
Adding retention time to SOIs names- RHermes shiny app

### ISSUE THREAD

**Issue by mvinaixa** [RogerGinBer/RHermes#2]
Dear @RogerGinBer, 

Regarding RHermes shiny app, the convention to name SOIs seems to be (SOI id number + formula adduct + intensity). I would appreciate adding retention time to the SOI names in SOI selector options within SOI exploration tab. This would help to quickly navigate SOIs

**Comment by RogerGinBer** [comment]
Hi @mvinaixa,

I'm currently working on it :+1:  Once it is working I'll commit the changes to the devel branch for the moment and, once we make sure everything is stable, we'll PR with the master branch
Feel free to comment on any other features you'd like to see in RHermes!

Roger
